spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tstdb?character=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: tstuser
    password: 123456
  redis:
    host: localhost
